# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

charToInt <- function(Seq) {
    .Call('microclass_charToInt', PACKAGE = 'microclass', Seq)
}

Kmer_count <- function(seqs, K, names) {
    .Call('microclass_Kmer_count', PACKAGE = 'microclass', seqs, K, names)
}

multinomClassifyCpp <- function(seqs, K, QMat, Prior, posterior) {
    .Call('microclass_multinomClassifyCpp', PACKAGE = 'microclass', seqs, K, QMat, Prior, posterior)
}

multinomTrainCpp <- function(seqs, K, names, classesIn, nPseudo) {
    .Call('microclass_multinomTrainCpp', PACKAGE = 'microclass', seqs, K, names, classesIn, nPseudo)
}

rdpClassifyCpp <- function(seqs, K, QMat, Prior, posterior) {
    .Call('microclass_rdpClassifyCpp', PACKAGE = 'microclass', seqs, K, QMat, Prior, posterior)
}

rdpTrainCpp <- function(seqs, K, names, classesIn, nPseudo) {
    .Call('microclass_rdpTrainCpp', PACKAGE = 'microclass', seqs, K, names, classesIn, nPseudo)
}

