# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

charToInt <- function(Seq) {
    .Call('microclass_charToInt', PACKAGE = 'microclass', Seq)
}

crossprodnum <- function(AA) {
    .Call('microclass_crossprodnum', PACKAGE = 'microclass', AA)
}

tcrossprodnum <- function(AA) {
    .Call('microclass_tcrossprodnum', PACKAGE = 'microclass', AA)
}

crossprodint <- function(AA) {
    .Call('microclass_crossprodint', PACKAGE = 'microclass', AA)
}

tcrossprodint <- function(AA) {
    .Call('microclass_tcrossprodint', PACKAGE = 'microclass', AA)
}

tcrossprodnumnum <- function(AA, BB) {
    .Call('microclass_tcrossprodnumnum', PACKAGE = 'microclass', AA, BB)
}

tcrossprodintint <- function(AA, BB) {
    .Call('microclass_tcrossprodintint', PACKAGE = 'microclass', AA, BB)
}

crossprodnumnum <- function(AA, BB) {
    .Call('microclass_crossprodnumnum', PACKAGE = 'microclass', AA, BB)
}

crossprodintint <- function(AA, BB) {
    .Call('microclass_crossprodintint', PACKAGE = 'microclass', AA, BB)
}

crossprodIntint <- function(AA, BB) {
    .Call('microclass_crossprodIntint', PACKAGE = 'microclass', AA, BB)
}

prodnumnum <- function(AA, BB) {
    .Call('microclass_prodnumnum', PACKAGE = 'microclass', AA, BB)
}

prodintint <- function(AA, BB) {
    .Call('microclass_prodintint', PACKAGE = 'microclass', AA, BB)
}

eprodnumnum <- function(AA, BB) {
    .Call('microclass_eprodnumnum', PACKAGE = 'microclass', AA, BB)
}

eprodintint <- function(AA, BB) {
    .Call('microclass_eprodintint', PACKAGE = 'microclass', AA, BB)
}

sseintint <- function(AA, BB) {
    .Call('microclass_sseintint', PACKAGE = 'microclass', AA, BB)
}

ssenumnum <- function(AA, BB) {
    .Call('microclass_ssenumnum', PACKAGE = 'microclass', AA, BB)
}

Kmer_count <- function(seqs, K, names) {
    .Call('microclass_Kmer_count', PACKAGE = 'microclass', seqs, K, names)
}

multinomClassifyCpp <- function(seqs, K, QMat, Prior, posterior) {
    .Call('microclass_multinomClassifyCpp', PACKAGE = 'microclass', seqs, K, QMat, Prior, posterior)
}

multinomTrainCpp <- function(seqs, K, names, classesIn, nPseudo) {
    .Call('microclass_multinomTrainCpp', PACKAGE = 'microclass', seqs, K, names, classesIn, nPseudo)
}

rdpClassifyCpp <- function(seqs, K, QMat, Prior, posterior) {
    .Call('microclass_rdpClassifyCpp', PACKAGE = 'microclass', seqs, K, QMat, Prior, posterior)
}

rdpTrainCpp <- function(seqs, K, names, classesIn, nPseudo) {
    .Call('microclass_rdpTrainCpp', PACKAGE = 'microclass', seqs, K, names, classesIn, nPseudo)
}

